### ISSUE TITLE
nuclei 能否使用-as功能

### ISSUE THREAD

**Issue by anquanbiji** [0x727/ShuiZe_0x727#104]
**描述**
看配置文件 nuclei配置 
`nuclei_config = -rl 300 -c 50 -timeout 5 -stats -silent -severity critical,high`  
这配置应该是跑所有的 high 以上漏洞吧? 会不会产生很多无效的请求? 
能加个 -as 参数，先使用 wappalyzer 进行指纹识别，在进行扫描? 

当然我可以自己在配置文件里面修改nuclei_config ，只是想确认下，-as参数是否有价值

**Comment by SkewwG** [comment]
感谢反馈，-as参数很有价值，后面会默认加上-as参数

**Comment by anquanbiji** [comment]
这个 -as 是基于[wappalyzergo](https://github.com/projectdiscovery/wappalyzergo)，最终的指纹库是 [wappalyzer](https://github.com/wappalyzer/wappalyzer/tree/master/src/technologies)，还是有一些误差
比如php的网站，wappalyzergo会识别出来php，然后把所有php的cms都跑一遍，我还没有想好怎样优化  

但比没有-as ,还是更近了一步

**Comment by SkewwG** [comment]
嗯嗯。已经更新了

**Comment by anquanbiji** [comment]
感谢
