### ISSUE TITLE
quake api未返回对应字段导致报错

### ISSUE THREAD

**Issue by Zimba5880** [0x727/ShuiZe_0x727#120]
使用quake api查询部分域名时会报以下错误
<img width="416" alt="image" src="https://user-images.githubusercontent.com/21590266/184058687-84cc59de-94b4-4e08-a972-ba4c817e0c0a.png">

测试发现似乎是quake api有时候返回的data里可能出现不存在`service.http.title`这个字段导致的

文件路径：
> Plugins\infoGather\WebspaceSearchEngine\quakeApi.py 

相关代码：
```python
if 'http' in service.keys():
    http = service['http']
    host = http['host'] 
    title = http['title']  # 此处为报错的第62行，由于返回数据里可能没有title这个字段导致报错
```

经测试使用dict get方法后即可正常运行，建议改成以下形式：
```python
if 'http' in service.keys():
    http = service['http']
    host = http['host'] 
    title = http.get('title','not exist') 
```

**Comment by SkewwG** [comment]
感谢师傅反馈，已修复

**Comment by 2328956238** [comment]
感谢，师傅
