### ISSUE TITLE
在运行到存活探测得时候会cpu跑满

### ISSUE THREAD

**Issue by ladyBird-z** [0x727/ShuiZe_0x727#56]
运行到存活探测得时候，探测到一半，然后就卡住，，cpu跑完，就kill掉了

**Comment by ladyBird-z** [comment]
是不是子域名太多得问题导致得？？

**Comment by ladyBird-z** [comment]
好像是添加fofa和shodan后，，资产太多请求过大得原因感觉

**Comment by SkewwG** [comment]
是的，我之前也发现过这个问题，后期有时间了我会再排查下该问题。

**Comment by ladyBird-z** [comment]
> 是的，我之前也发现过这个问题，后期有时间了我会再排查下该问题。

感谢
