### ISSUE TITLE
Centos7运行，加载配置文件报错

### ISSUE THREAD

**Issue by 2632980713** [0x727/ShuiZe_0x727#67]
--------------------------------------------------Load ksubdomain ...--------------------------------------------------
./Plugins/infoGather/subdomain/ksubdomain/ksubdomain_linux: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory
[total: 0] ksubdomain: []
len [0]
[total: 0] theHarvester: []
len [0]
--------------------------------------------------Load VirusTotal threatcrowd url.fht.im ...--------------------------------------------------
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/root/ShuiZe_0x727/ShuiZe.py", line 1567, in <module>
    _init()
  File "/root/ShuiZe_0x727/ShuiZe.py", line 1484, in _init
    run_subdomain()
  File "/root/ShuiZe_0x727/ShuiZe.py", line 1011, in run_subdomain
    othersApiTotalSubdomains = othersApiSubdomain()
  File "/root/ShuiZe_0x727/ShuiZe.py", line 260, in othersApiSubdomain
    othersApiTotalSubdomains = othersApiRun(domain)          # 列表，存放子域名
  File "/root/ShuiZe_0x727/Plugins/infoGather/subdomain/othersApiSubdomains/othersApiSubdomains.py", line 410, in othersApiRun
    init(domain)
  File "/root/ShuiZe_0x727/Plugins/infoGather/subdomain/othersApiSubdomains/othersApiSubdomains.py", line 401, in init
    securitytrailsApi = cf.get('securitytrails api', 'Securitytrails_API')
  File "/usr/local/python3/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/python3/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'securitytrails api'

**Comment by history3** [comment]
你这个可以试试

运行提示缺少 xxx.so 等依赖
// Ubuntu
apt-get install -yq --no-install-recommends \
     libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
     libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
     libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libgbm1 \
     libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3
     
// CentOS 7
sudo yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 \
     libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 \
     ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y

sudo yum update nss -y
